### ISSUE TITLE
 Bug: Failed to Load Reloaded-II when a launcher launches the game case insensitively 

### ISSUE THREAD

**Issue by Albeoris** [Reloaded-Project/Reloaded-II#106]
Related:  #51
Game: [Final Fantasy VIII](https://store.steampowered.com/app/39150/FINAL_FANTASY_VIII)

**Describe the Bug**
After installing ASI Loader, an error appears when starting the game. 
```
Failed to Load Reloaded-II. Unable to find a configuration for the currently executing application.
at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
at Reloaded.Mod.Loader.EntryPoint.LoadMods()
at Reloaded.Mod.Loader.EntryPoint.ExecutiveTimed(String text, Action action)
at Reloaded.Mod.Loader.EntryPoint.SetupLoader()
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Add "\SteamApps\common\FINAL FANTASY VIII\FF8_EN.exe"
2. Install and activate any mod.
3. Launch the game via FF_Launcher.exe

**Expected Behaviour**
Loading the mod without any errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4787832/141650770-f7cc64e1-93d3-4efa-80a5-8586be4d6b23.png)
![image](https://user-images.githubusercontent.com/4787832/141650339-6ae91ebf-b349-4843-a283-20244fcf249f.png)
![image](https://user-images.githubusercontent.com/4787832/141650321-9939dde2-9945-445a-92dd-001f1ee69080.png)

**Additional Context**
The launcher launches the game using lower case names and / slashes. The Reloaded configuration specifies the real path to the image. Both paths are normalized, but normalization does not change the case of the path. We then compare the two paths in a case-sensitive manner. The paths do not match, the error is thrown.

On Windows, paths must be compared in a case-insensitive manner.
The error message is missing an indication of which path was not found.

**Comment by Sewer56** [comment]
Absolutely solid.
Well explained, well checked and easy fix (since Windows itself is case insensitive, even if e.g. NTFS itself is case sensitive).

I can quickly patch this up and roll a hotfix if it's blocking you; otherwise, next patch is probably around a month away.

I've been working on an update library of my own and I'm almost done on that front; after that I'll be working with R-II code again to integrate it and make some user friendliness related changes. I do plan to ship a separate setup application and a quick setup on the launcher on first launch itself; as well as changes that improve the overall update related experience.

**Comment by Albeoris** [comment]
The next patch sounds great.
As a workaround, I've converted the letters to lowercase in the config of App.
