### ISSUE TITLE
Bug: Crash on boot in Proton

### ISSUE THREAD

**Issue by geferon** [Reloaded-Project/Reloaded-II#111]
**Describe the Bug**
Trying to launch Reloaded 2 with Proton launches the error

> Object reference not set to an instance of an object
>  at Reloaded.Mod.Launcher.Lib.Utility.WmiProcessWatcher.Dispose()
>  at Reloaded.Mod.Launcher.Lib.Utility.WmiProcessWatcher.Finalize()

**Screenshots**
![image](https://user-images.githubusercontent.com/7958349/164864737-fbba5f01-c850-4a2a-aefd-31028ceadc1d.png)

**Additional Context**
I'm currently trying to get Reloaded 2 to run on the Steam Deck, and although I've managed to install VCRedist and NET 5 on it, I'm currently getting this error which seems to be caused by WMI trying to be used on Linux.
The problem seems lie here:
https://github.com/Reloaded-Project/Reloaded-II/blob/88a05cb1832240e3adcaffee164065e321a8554e/source/Reloaded.Mod.Launcher.Lib/Utility/Interfaces/IProcessWatcher.cs#L31
As although the comment acknowledges Wine, it still implements the WMI watcher on it.

**Comment by Sewer56** [comment]
Usually under Wine it fails at instantiation rather than disposal; hence the exception handling fallback.  
Guessing some internal changes, either to Proton or Wine itself added partial WMI support at some point; seeing it didn't fail here anymore.  

When I wrote this code, I didn't have explicit Wine checks; and just relied on the occasional bug report to test.  
Anyway, I added an explicit Wine check here in the latest hotfix.  

Can you check if the issue still reproduces?

**Comment by geferon** [comment]
Yep! No longer crashes, thanks a bunch!
