### ISSUE TITLE
Bug: Message "Reloaded config has not been found" when trying to launch via ASI on Steam via proton

### ISSUE THREAD

**Issue by magomagal** [Reloaded-Project/Reloaded-II#125]
Edit: Forgot to say I am playing Sonic Heroes
Running the game via the launcher works, but trying to use DLL injection gives me the message "Reloaded config has not been found"
When I press the "Open config file" on reloaded, nothing happens and I get these lines on the terminal (Only the lines after 05fc):
![Screenshot_2022-07-18_20-35-17](https://user-images.githubusercontent.com/80652132/179634251-7f0fb92f-beca-450f-aead-fe23c286b2b7.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Added game executable "Tsonic_win.exe" on steam
2. Put "WINEDLLOVERRIDES="DSOUND.dll=n,b" %command%" on launch options, without it game just loads without any mods.
3. Get error and game launches without any mods loaded.

**Screenshots**

![Screenshot_2022-07-18_19-53-26](https://user-images.githubusercontent.com/80652132/179633091-21118346-b6aa-4d35-a6c0-5cdf7dc1f501.png)
![Screenshot_2022-07-18_20-08-40](https://user-images.githubusercontent.com/80652132/179633095-00fa06d1-707c-4754-8f16-b59b35119b30.png)

**Comment by Sewer56** [comment]
I've never ran R-II on Proton myself, although I do fix Wine related issues where possible.  

In any case, I've heard of people have this issue before, based on their reports it usually boils down to:  

- Proton creates a separate WINEPREFIX for each game.  
- So instead of your user folder being in `/home/$USER/.wine/drive_c/users/$USER/`, it's in a folder like "/home/$USER/.steam/debian-installation/steamapps/compatdata/$STEAM_ID/pfx/drive_c/users/steamuser".

If you copy the AppData folder from the first folder (default Wine user folder) to the second folder (Steam created user folder), it should work.  

There's a lot more usage coming out of Proton lately, likely due to release of the Deck; I'll probably need to see if it's possible to make some awareness check for when it's running from a WINEPREFIX with custom user folder.

**Comment by magomagal** [comment]
I copied the folder and this time it just crashed before opening the game, I tried using Proton 7.0.3, Experimental and GE-Proton-7-20.
![image](https://user-images.githubusercontent.com/80652132/179776240-e23cf65f-a6de-4d2d-adec-ddf33b7dedfb.png)

### [Reloaded II Bootstrapper] Ultimate ASI Loader Entrypoint Hit
wine: Unhandled exception 0xe06d7363 in thread 198 at address 7B0111B7 (thread 0198), starting debugger...
Unhandled exception: C++ exception(object = 0x0240fccc, type = 0x02202cb4) in 32
-bit code (0x7b0111b7).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b0111b7 ESP:0240fbe4 EBP:0240fc58 EFLAGS:00000203(   - --  I   - - -C)
 EAX:0240fbf0 EBX:e06d7363 ECX:00000000 EDX:0240fc04
 ESI:0240fc94 EDI:0240fc0c
Stack dump:
0x0240fbe4:  00000002 00000040 0240fc2c e06d7363
0x0240fbf4:  00000001 00000000 7b0111b7 00000003
0x0240fc04:  19930520 0240fccc 02202cb4 7bc6a3e0
0x0240fc14:  00000000 0240fc2c 00000040 7bc6a8a0
0x0240fc24:  0240fc40 0240fd08 024701b0 00e4c8e0
0x0240fc34:  7bc6a39c 0240fc54 00000040 00000040
Backtrace:
=>0 0x7b0111b7 AccessCheckByTypeAndAuditAlarmW+0x101b7() in kernelbase (0x0240fc
58)
  1 0x021c49c7 EntryPoint+0xee8() in reloaded.mod.loader.bootstrappe (0x0240fc98
)
  2 0x02193581 in reloaded.mod.loader.bootstrappe (+0x3581) (0x0240ff2c)
  3 0x02192765 in reloaded.mod.loader.bootstrappe (+0x2765) (0x0240ff48)
  4 0x7bc5d9d7 A_SHAFinal+0x3d337() in ntdll (0x0240ff5c)
  5 0x7bc5e180 A_SHAFinal+0x3dae0() in ntdll (0x0240ffec)
0x7b0111b7 kernelbase+0x111b7: subl     $4,%esp

Hope you enjoy your vacation!

**Comment by Sewer56** [comment]
Well, shit, this is the least helpful sort of error message I can actually get, aaaaaa.

Can you install `protontricks` and make sure the following are available in the `wineprefix` used for your game? (using `protontricks`)

- Visual C++ Runtime 2015 (x86, or newer)
- .NET 5 Desktop Runtime (x86)

That might resolve the issue since there's a good chance that you run the launcher in the default `wineprefix` but the game in another one, leading to possible missing dependencies. 

-----

In all fairness this is something I need to work on; with the release of the Deck there's a lot of new Proton users around while R-II was usually only tested under Wine (mostly by end users, I don't boot the VM often during development).

**Comment by magomagal** [comment]
I installed these two dependencies and it worked! The game launched and loaded the mods.
There's only a weird issue where running the game with Proton has a very poor performance (At least for me) and I can't even get past the title screen as it seems to not accept inputs or something while also being very laggy, though it also happens without loading Reloaded II so I assume it's something outside the scope of this Issue report and the mod loader itself.
Thank you for your help!

**Comment by magomagal** [comment]
Unfortunately `d3d8to9` didn't help, and the remapping mods work fine via wine it's just an issue with Proton apparently(?), I even tried a bunch of proton enviroment variables but it still ran very slow.
The game does run just fine with Wine which is great!

**Comment by Sewer56** [comment]
The world can be strange /shrug .
If it works, it works.

**Comment by BrianAllred** [comment]
Asking here since my probably is very similar.

I'm using Reloaded II to mod Persona 5 Royal on Linux (not Steam Deck). However, I followed [this tutorial](https://gamebanana.com/tuts/15409) (substituting for the correct paths), and everything went well. I was able to install and configure a couple of mods.

However, I'm getting a similar bootstrap error as OP when launching the game.

Launch options set to `WINEDLLOVERRIDES="dinput8=n,b" %command%`.

![image](https://user-images.githubusercontent.com/5847511/201551171-52ec5778-5439-47fd-bd98-9e4381290285.png)

**Comment by Sewer56** [comment]
If you are using Proton, have you tried running the Reloaded Launcher from your proton prefix (at least once) before launching game?

This error usually shows up when the C++ bootstrapper reads the config file in `%appdata%/Reloaded-Mod-Loader-II/ReloadedII.json` and the path in `LoaderPath32`/`LoaderPath64` does not point to a valid file.

These paths are usually updated on Launcher boot.

**Comment by BrianAllred** [comment]
Ahhhh, that led me to the solution. I'm using the Flatpak version of Steam, and it didn't have permission to access the directory Reloaded lived in. I moved stuff around, relaunched Reloaded, everything works great now. Thank you!!
