### ISSUE TITLE
Help: Running reloaded on Steam Deck

### ISSUE THREAD

**Issue by orah28** [Reloaded-Project/Reloaded-II#126]
**Did you install the Prerequisites?**
Yes

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
When I go and launch my modded version of Persona 4 Golden on my Steam Deck, i get an errorr message. I've attached a photo of the error. Reloaded can find persona 4 golden when I go and set it and I've made sure the mod folders are in the right places. 
![20220721_155033](https://user-images.githubusercontent.com/109697346/180300015-55988cdd-13d3-4cf9-a026-35794f6a57a7.jpg)

**Screenshots**

**Additional Resources**
I got the guide I used from the persona modding discord

**Comment by Sewer56** [comment]
Might be Symbolic Link (SymLink) shenanigans.

Your file path might be set to something like: 
`Z:/home/deck/.steam/steam/steamapps/common/Persona 4 Golden/P4G.exe` 

But the real path of the file might be something like:
 `Z:/home/deck/.local/share/Steam/steamapps/common/Persona 4 Golden/P4G.exe`

The loader only normalizes the file path to find the currently executing game; and currently doesn't resolve symlinks (IIRC, been a while since I wrote that code), it's something I should doublecheck at some point.

**Comment by orah28** [comment]
I just reinstalled reloaded and it seems to work fine now. I'm not sure why I didn't try that first. Thanks for the help anyway

**Comment by AssisrMatheus** [comment]
I'm also having the same problem. Even reinstalling and making sure I wasn't on a symlink folder worked:
https://cdn.discordapp.com/attachments/262183267665575936/1000393162050768987/2022-07-23_09-21-53.mp4

**Comment by Sewer56** [comment]
Potentially related:

Executable path doesn't actually get saved to the config file until you leave the menu (go to another menu/close the window) or start the game from the launcher.  
So in the case of the video, setting a new path wouldn't have had an effect until the menu was navigated away from. The path set at the end of the clip was (probably) correct.
