### ISSUE TITLE
[User Had Issue with OS Locale]

### ISSUE THREAD

**Issue by Joaquin-123** [Reloaded-Project/Reloaded-II#175]
When trying to do the Launch Application step, I get this error: 

![Captura de pantalla (7891)](https://user-images.githubusercontent.com/71752979/209654303-a0133543-cd4a-44c0-bc56-e949dac3f708.png)

I haven't found how to solve it

**Comment by Sewer56** [comment]
Hace you tried the advice listed in the error?

**Comment by Joaquin-123** [comment]
Yep, I've tried, and also the antivirus seems to not be a problem

**Comment by Sewer56** [comment]
Are you absolutely sure the R2 install itself isn't just borked?

Usually you'd get a more detailed error message, this one is actually more of a fallback.

**Comment by Joaquin-123** [comment]
I just followed the tutorial https://p4g.cep.one/reloaded-ii

Should I download again?

**Comment by Sewer56** [comment]
Feel free to try, and let me know.

**Comment by Joaquin-123** [comment]
Ok, will do, maybe it's just bad luck with the download or something

**Comment by Joaquin-123** [comment]
Nope, same thing happened

**Comment by Joaquin-123** [comment]
Ok, I solved it, it was my locale language, thanks anyway

**Comment by Sewer56** [comment]
Could you let me know what your original locale was? I'd be interested in debugging this.

**Comment by Joaquin-123** [comment]
I had it on Japanese to play some old Japanese games some time ago, I remembered that, and changing it to my original locale (Spanish) worked. It may have to do with how the japanese one changes some symbols, like the '/' I think, which is changed to the yen symbol.

**Comment by Sewer56** [comment]
I'll need to have a look at this sometime then :3

**Comment by Sewer56** [comment]
I'm surprised this was left open for so long.
In any case, I tried replicating, setting Locale, Language and Time/Date Format to Japanese (without that UTF-8 experimental feature).

Tried across a variety of games (including those by Japanese devs), things worked just fine. Of course path separator `/` got changed to yen symbol, but that's normal.

I know at one point there was a temporary breakage where Unicode paths got broken as I moved to a more lightweight JSON parser, however that was fixed in less than a week. Not sure if that was related.

I'll close this as 'can't repro', maybe it got fixed along with something else at some point.
