### ISSUE TITLE
Request: Please Add Ability to use a Slider Control for Mod Config settings

### ISSUE THREAD

**Issue by jroweboy** [Reloaded-Project/Reloaded-II#202]
**Is your feature request related to a problem? Please describe.**

I'm developing mods that have several numeric inputs limited to specific ranges, and the configuration control for numbers are only input texts with a up and down option on the end. I feel if we can have a slider as an option for numeric input that it would be considerably easier for users of the mod to properly configure these fields.

**Describe the solution you'd like**

I don't usually do feature requests as I feel like if I really want it I'll just do the coding myself, but I'm kinda running into a wall with how to implement the feature. What I'm picturing is a new annotation that determines which control to use. Each field can continue to have a default control like they currently do, but if theres an annotation on the field for the new option, it'll use that one instead. Additionally, there would be other new annotations to configure the controls, which could even be useful for the default controls.

Here's a code sample for how I think the API could look

```cs
    [DisplayName("Background Music Volume")]
    [Description("Controls the volume for in game background music.\nRange: 0-100 where 0 means mute")]
    [DefaultValue(100)]
    [Control("Slider")]
    [SliderControlParams(0, 100, 1)] // Min, Max, Step
    public int MusicVolume { get; set; } = 100;
```

Having the ability to customize the current Number Control fields `min`, `max`, and `step` values would go a long way as well, if adding the Slider control is too much effort right now.

**Describe alternatives you've considered**

I traced through the code to find where the specific controls are selected, but from PropertyGridEx, I haven't a clue how i would get the annotation values as required to choose a slider control instead of a numeric control in this class. I feel like directly accessing the annotations here would be kinda backwards too, but I don't have the experience in the Reloaded codebase to know where I would change the architecture to add such a thing either. https://github.com/Reloaded-Project/Reloaded-II/blob/319250525bf8facfc95cd976f3eba3068c72c801/source/Reloaded.Mod.Launcher/Controls/PropertyGridEx.cs#L72-L112

**Additional context**

I did a little digging into the library used `HandyControl` and they have sliders of course thankfully ^^; but i don't have the context to know how to make something outta this haha.

**Comment by Sewer56** [comment]
Hi,👋

Thanks for the feature request. I think the idea for a slider control in the configuration options sounds quite useful. I understand that implementing this might be a bit challenging to wrap your head around, so here's a possible approach to make it work:

## Creating the Attribute

First, let's create a new attribute in the `Reloaded.Mod.Interfaces` library for the slider control:

```csharp
// Reloaded.Mod.Interfaces.Structs
public class SliderControlParamsAttribute : Attribute
{
    public int Min { get; }
    public int Max { get; }
    public int Step { get; }

    public SliderControlParamsAttribute(int min, int max, int step)
    {
        Min = min;
        Max = max;
        Step = step;
    }
}
```

The reason this attribute would need to exist in `Reloaded.Mod.Interfaces` is because this package defines the contract between a mod and the launcher. The library is loaded by the launcher, and the mods force load the launcher's version; and thus both can agree on what a `SliderControlParamsAttribute` is.

Now, we can use this attribute in your mod to define the slider control parameters, just like you mentioned in your code sample, i.e.

```csharp
[SliderControlParams(0, 100, 1)]
```

## Modifying the PropertyGrid

To add support for a custom control in the `PropertyGrid`, you would need to do the following.

- Add a field in `PropertyResolverEx` storing current `PropertyDescriptor`.  

```csharp
public PropertyDescriptor Descriptor { get; set; }
```

- Assign this field in `CreatePropertyItem` method.  

```csharp
protected override PropertyItem CreatePropertyItem(PropertyDescriptor propertyDescriptor, object component, string category, int hierarchyLevel)
{
    PropertyResolver.Descriptor = propertyDescriptor;
    // existing code below
```

- Get the Attribute

The `base.CreatePropertyItem` will end up calling `CreateDefaultEditor(Type type)` down the road.
You can then get the `PropertyDescriptor` back from the field and test for your attribute via:

```csharp
PropertyDescriptor.Attributes.OfType<SliderControlParamsAttribute>().FirstOrDefault();
```

Then just implement another editor, e.g. a version of `NumberPropertyEditor` that instead spawns a slider.  

## Caveats

The interfaces/contracts defined in `Reloaded.Mod.Interfaces` have to be carefully planned.  
Any APIs added there can never be broken/removed to ensure backwards compatibility.

**Comment by Sewer56** [comment]
Now that I'm employed I don't have quite the time I used to have to maintain the silly amount of repos I have; and I still got some other projects and issues in the backlog 😅.

If you'd like to contribute however, hopefully that should be sufficient information to do so.

**Comment by jroweboy** [comment]
Thanks for the advice! I am just getting started on this project now, and I'm wondering if there's a good way to create a test mod that I can add and test out the new controls with. I found the testing folder with test mods, but none of them include a configuration. Is it better to make my own test project in that folder? If so, what would be a good application that I could set for the AppID so i can find it in the launcher to open its configuration?

**Comment by Sewer56** [comment]
The difficult part about debugging is the fact a mod needs to have the absolute latest version of `Reloaded.Mod.Interfaces` from inside your fork of R2.

Easiest way to test would probably be temporarily editing `Reloaded.Utils.Server` [just don't commit by addicent]. It's already in this repo, has a config and uses local version of `Reloaded.Mod.Interfaces`.

As for AppId, there's a flag you can set in your ModConfig `IsUniversalMod` to true. If enabled your mod will show up in all games.
