### ISSUE TITLE
P4G: Reloaded Mod Loader DDL not found Steam Deck

### ISSUE THREAD

**Issue by LegendDarkness97** [Reloaded-Project/Reloaded-II#208]
Note: Using SteamOS on Steam Deck
Followed the instructions on https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide/
and also manually installed the dependencies from https://github.com/Pixelguin/Persona.PrerequisiteInstaller (after the error first occured)
both into the general wine environment and the P4G wine environment from Steam
I also restarted my Steam Deck for good measure and tested it both in Desktop and Steam Mode
I always get the error message "Reloaded Mod Loader DLL has not been found"

**Comment by Sewer56** [comment]
Can you do the following:

- Hit `Open Config File` in Launcher.
  - If this does nothing, hit `View Log Files`, go a folder up and open `ReloadedII.json`
- Take a screenshot or copy/paste the line with `LoaderPath64`,

I'm guessing it tries to find the path specified there but it can't because it's in a different WINEPREFIX, or something of the sort.
If you launch the launcher from game's WINEPREFIX, it might resolve the issue.

**Comment by LegendDarkness97** [comment]
Changed the that path and all the other ones to point to the correct location, but now it crashes with the error "Failed to read unloaded module data". A memory access error (reading memory something) is listed directly beforehand, but the console closes to fast to get more information.
Afterwards the console closes immediately and the errors aren't written to the log files.
Disabling any or all mods doesn't change these errors.
The "AWB Emulator Support for CRI Filesystem V2 Hook" and "File Emulation Framework: Base Mod" have a filled red square with grey border in the enable/disable column and can't be activated manually.
Reloaded II  itself is also prone to crashing with an internal .NET Runtime error

**Comment by Sewer56** [comment]
Not sure on the status on this. At time of writing, Wine has issues running .NET 7 in some circumstances, but I know that's been since fixed.
