### ISSUE TITLE
Bug: The program is not opening. 

### ISSUE THREAD

**Issue by cuzl** [Reloaded-Project/Reloaded-II#225]
I've downloaded the setup file and it seems to have installed, but it won't open. It says it's suspended in task manager for a second and then closes itself.

**Comment by AFriendlyIrin** [comment]
I had the same problem when I attempted to run Reloaded II from an external flash drive. Is it installed to your hard drive?

**Comment by cuzl** [comment]
I found a solution shorty after asking this and never responded. Oops. I had to open Reloaded II from the WinRar file, but it doesn't open when I extract it. I don't understand why, but hey, it works for me now. Also yes, it is on my hard drive. I hope this helps.

**Comment by AlmightyLks** [comment]
Have you ever checked your Windows defender for deleted files?
Windows Defender can't mess with files within archives. That might be the reason why it might work from in there
Though executables ran from within archives can't load .dll dependencies, so that's surprising me. I wonder if the Windows Event Manager is saying anything? 

Also, FYI: Use 7Zip instead of WinRaR 😜 They've got no right of existence at this point
