### ISSUE TITLE
Help: Reloaded II does not properly load P5R mods

### ISSUE THREAD

**Issue by DunwallRaven** [Reloaded-Project/Reloaded-II#231]
The game itself launched normally when launching through Reloaded. However, only Persona Essentials is working (as it skips the intro), and it appears that other mods are not loaded properly and nothing is changed in-game. Thank you for your work anyway.

I have the following mods installed:
![01](https://github.com/Reloaded-Project/Reloaded-II/assets/134210292/41906f3f-aff0-4fe0-8083-14878ce5014d)

Here's the log when launching the game:
[report.txt](https://github.com/Reloaded-Project/Reloaded-II/files/11524648/report.txt)

**Comment by Sewer56** [comment]
Boot the game and navigate to the final line which says 'Bind Complete'.

While the game is still running, verify if there's anything in the target folder.

**Comment by DunwallRaven** [comment]
Thanks for the fast response. There are things there, but the folders appears to be empty as the file size are 0:
![03](https://github.com/Reloaded-Project/Reloaded-II/assets/134210292/e71e9ccd-3644-437d-81a0-2b24790a442c)

**Comment by Sewer56** [comment]
Welp, I was typing a response and then phone browser crashed and I lost it.

Anyway; most likely the drive you have your mods on doesn't support hardlinks; which prevents files from being linked over.  

This is because CriFsV2Hook (CRI FileSystem V2 Hook) mod that enables injecting assets, relies on all files being stored in one folder before being dynamically loaded into the game.  

There was a solution in the works which would have prevented this, however; I cannot release it due to a technical reason. (It would eventually break on higher .NET versions and was already broken on Wine today). So I have to rewrite that entire thing, and another project too, outside of C#.

Anyway, just moving your `Mods` folder should be sufficient. The easy way to do it is just moving the entire Reloaded folder. 

The harder, more flexible way is to: 
- Open the Config
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/c6e5231f-55d6-4114-b621-39f1ad5d58e5)

- Close the Launcher

- Edit the Mods Path
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/c7454927-c38d-4c69-ab63-267f6717a8b3)

- Open the Launcher

**Comment by DunwallRaven** [comment]
Thanks for the response. Could you maybe specify on what type of drive may or maynot support hardlinks? I did have my reloaded ii and my mod folders on a portable drive, maybe that has something to do with it?

**Comment by Sewer56** [comment]
Usually on Windows any NTFS formatted drive should be okay (and for Linux, ext4).
If it's an external drive that's not playing ball well; I'm guessing it's probably `exFAT`.

Moving to your main drive should be okay.

**Comment by Sewer56** [comment]
Sorry for the inconvenience; it was supposed to be fixed by now; just a roadblock set things back by a few months.

**Comment by DunwallRaven** [comment]
Well moved the reloaded ii folder to my internal drive and it finally worked, thank you very much for the fast and useful responses :D

**Comment by Sewer56** [comment]
No problem; have fun :p

Oh, and remember to turn off the debug settings in some of the mods. You had AWB dumping enabled in your logs for example.
