### ISSUE TITLE
Help: Sonic Heroes Issue Please Help

### ISSUE THREAD

**Issue by LEtSPlAy096** [Reloaded-Project/Reloaded-II#235]
Hi I was trying to run the modded version of Sonic Heroes but I keep getting this error message stating s*** the program crash in application code can you help

**Comment by Sewer56** [comment]
Take a screenshot of the problem

**Comment by LEtSPlAy096** [comment]
![Uploading IMG_0141.jpeg…]()

**Comment by LEtSPlAy096** [comment]
#
![IMG_0141](https://github.com/Reloaded-Project/Reloaded-II/assets/136738243/f9d70fcd-77cc-4040-8e8c-370abe0ec953)

**Comment by Sewer56** [comment]
Since it is in your downloads folder; can you verify if game works without using any mods?

Take a screenshot of your game folder; maybe it's a pre-modded copy with some old patches.

**Comment by LEtSPlAy096** [comment]
It won’t launch with reloaded but it will with the original game 
![IMG_0141](https://github.com/Reloaded-Project/Reloaded-II/assets/136738243/21b7c4e7-6d1f-4524-9639-a76c44bda86b)
![IMG_0142](https://github.com/Reloaded-Project/Reloaded-II/assets/136738243/420bb3ee-61e6-4b1b-afce-ddc8c0f78061)

**Comment by Sewer56** [comment]
Can you take a picture of actual game folder? I need to know if it's been modified prior ; some people host/upload pre-modded copies.

**Comment by LEtSPlAy096** [comment]
![IMG_0143](https://github.com/Reloaded-Project/Reloaded-II/assets/136738243/dacbd37d-35d7-4ac4-8e80-ec55a0be0925)

**Comment by LEtSPlAy096** [comment]
You still there

**Comment by Sewer56** [comment]
Sorry, I am there, but just not at home (am out and about shopping), thus I can't answer immediately.

People don't usually use throw the mod loader into the game folder.

That said, aside from that, everything looks mostly okay; so abnormal behaviour is unexpected. 

I'd try toggling mods on and off individually, see if it's perhaps some random mod.

You can also try using an modified exe https://cdn.discordapp.com/attachments/745946574722433065/1094690042477301800/Tsonic_win.EXE ,see if it helps.

Otherwise throw yourself in this Discord server https://discord.gg/w65FWZ7 if time is of the essence.

**Comment by LEtSPlAy096** [comment]
It worked thanks for the help and I’m sorry if I disturbed your shopping

**Comment by Sewer56** [comment]
Don't worry, you're all good. Have fun 👏
