### ISSUE TITLE
Help: Please help me with P3P mod causing Reloaded II to not load on Steam Deck

### ISSUE THREAD

**Issue by MatthiasCrow** [Reloaded-Project/Reloaded-II#244]
**Did you install the Prerequisites?**
All prerequisites are installed

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
I'm trying to get a mod called Field QoLs (https://gamebanana.com/mods/456191) to work on Steam Deck. Any time I try to launch P3P I get an error stating "The provided stream & offset pairs don't form a complete file." whenever I disable it, everything works just fine. I've attached a copy of the log if it would help pinpoint the issue.
[2023-07-26 23.34.24 ~ P3P.txt](https://github.com/Reloaded-Project/Reloaded-II/files/12178153/2023-07-26.23.34.24.P3P.txt)

**Comment by Sewer56** [comment]
Reportedly this can happen when someone has an outdated copy of Persona Essentials, or so I've heard.

If it didn't auto update, nab it manually 
https://github.com/Sewer56/p5rpc.modloader/releases/download/2.3.0/p5rpc.modloader2.3.0.7z

And throw over the files in your existing download folder.

**Comment by MatthiasCrow** [comment]
It's still throwing the same error up unfortunately. I checked to make sure it showed up as 2.3.0 in Reloaded II as well.

**Comment by Sewer56** [comment]
Maybe @AnimatedSwine37 knows, they've seen this before

**Comment by AnimatedSwine37** [comment]
It looks like this is either a bug with Persona Essentials or PAK Emulator (I'm not exactly sure which one yet). 

This isn't the same as what happened the other day, instead of bf emulator being missing, some of the bfs are failing to be extracted for some reason. I'm getting a similar error with Field QoLs so I'll try and fix it and update you both when I do.

**Comment by AnimatedSwine37** [comment]
I've just realised that the error I was getting (which was similar but not the same) was actually because of mod menu being incorrectly formatted, it's unrelated to this unfortunately.

I think the problem is being caused by some `Path` functions being used when trying to extract files from the paks. Given you're using Linux they are probably acting differently, causing the problems.

I don't have a Linux environment with Reloaded and stuff setup currently so I'll have to do all that first, then hopefully I can work out a solution.

**Comment by MatthiasCrow** [comment]
I see, that sounds likely because my Windows PC has no issues loading up the exact same mods I use on the Deck. I appreciate all the help so far!

**Comment by MatthiasCrow** [comment]
Moving the P3P install from my micro sd to the internal drive fixed the issue. Here's the updated log.
[2023-07-27 01.39.54 ~ P3P.txt](https://github.com/Reloaded-Project/Reloaded-II/files/12178585/2023-07-27.01.39.54.P3P.txt)

**Comment by AnimatedSwine37** [comment]
That's interesting, maybe the two drives have two different file system types and that's somehow causing a difference.
Would you be able to check the file system type of the two?

**Comment by MatthiasCrow** [comment]
Both of them are showing up as ext4 and the micro sd is mounted at /run/media.

**Comment by Sewer56** [comment]
That is one of the strangest occurrences I've heard of.

Nothing immediately comes to mind (if it was a permissions problem, things would be way more broken). Hmmm
