### ISSUE TITLE
Bug: <Persona 5 Royal Crashes> when <I click launch application in Reloaded II>

### ISSUE THREAD

**Issue by neelysm** [Reloaded-Project/Reloaded-II#254]
Whenever I click launch application for P5R it crashes right away. The game will load up into a black screen then it just crashes. I tried this in Reloaded II 1.2.5 and 1.2.4 with the same results.

**To Reproduce**
Steps to reproduce the behaviour:
1. I launch reloaded
2. The loader for it pops up
3. Persona 5 Royal itself actually opens to a black screen and crashes

**Additional Context**
The runtimes are up to date and I only have Persona Essentials and Persona 5 Royal Custom Tweeks enabled. 
![Help](https://github.com/Reloaded-Project/Reloaded-II/assets/79173384/732e43c9-a783-4fa5-9a75-e39d0e74bfa7)
There is one more thing below in the list which is the PAK Emulator for File Emulation Framework

**Comment by Sewer56** [comment]
Does this happen with no mods enabled too?

If it works with mods disabled, can you toggle them individually and find the culprit?

**Comment by neelysm** [comment]
Yes, when the mods are disabled with just the CRI FileSystem V2 Hook and AWB Emulator enabled it still crashes

**Comment by Sewer56** [comment]
Is it the CRI Hook? That was overhauled recently.

If it is, you can see what happens with an older version: https://github.com/Sewer56/CriFs.V2.Hook.ReloadedII/releases/download/2.1.6/CriFs.V2.Hook2.1.6.7z , extract over current mod files

**Comment by neelysm** [comment]
That did not work. Now the loader thing just gets stuck here
![Stuck](https://github.com/Reloaded-Project/Reloaded-II/assets/79173384/4959e885-13c2-4a60-8697-eed1e97129a1)

**Comment by Sewer56** [comment]
That's a common-ish occurrence that happens to a few people (myself included when testing). It should work after trying to run the game a few times.

It will eventually be fixed one day but it requires a rewrite (for technical reasons) of a very big project in a completely different programming language. It'll take a long time.

**Comment by neelysm** [comment]
So am I just supposed to keep trying to run it? It did just open once but then it crashed again right afterwards.

**Comment by Sewer56** [comment]
That is kinda weird. Just with CRI Hook? What happens if you run with exactly 0 mods?

**Comment by neelysm** [comment]
Yup, when I run it with just the CRI Hook version 2.1.6 it still crashes

**Comment by neelysm** [comment]
The only thing else on are the things with the solid red boxes which I can't uncheck

**Comment by Sewer56** [comment]
I mean literally no mods at all, I'm curious if it has anything to do with loader itself

**Comment by neelysm** [comment]
It's the same thing even with no CRI Hook. It gets to the loader, opens the game, then crashes

**Comment by Sewer56** [comment]
That is pretty weird. Especially since loader itself doesn't modify the game. 

At least I know it's not one of the mods, but something really strange is going on.

I assume vanilla game via Steam runs correctly right?
Are you running any other external mods? (ReShade, etc.)

**Comment by neelysm** [comment]
Steam does open the game properly. I did have opened flawless widescreen and I think that was causing the issue. It seems to be running now without any mods opened through Reloaded II

**Comment by neelysm** [comment]
It seems to be working fine now, thank you for the help!

**Comment by Sewer56** [comment]
It was never fully investigated (so not 100% sure on this) but based on what I remember reported originally in 2022, I suspect Flawless Widescreen likely has an issue with its hooking code where it can't find memory to allocate once the .NET Runtime (used by Reloaded) is loaded into the game process. 

I presume it's because they only look forward from a given address, rather than also looking backwards, and the .NET Runtime reserves a large amount of memory space of front.

Flawless Widescreen is closed source, so we can't really study its code, debug it and submit (pull request) a fix. Not without spending a lot of time reverse engineering it. It's unfortunate.

I'm not sure if anyone actually tried contacting the author of FWS, maybe they're happy to debug with the community, and work on a fix; I'm not really sure if anyone has tried asking.

Anyway, have fun :P.
Make sure to update the CRI mod to latest again; there's a big performance bump.
