### ISSUE TITLE
Bug: Reloaded failing to launch P5R half the time

### ISSUE THREAD

**Issue by Jax765** [Reloaded-Project/Reloaded-II#263]
When I launch the game, either from a shortcut or Reloaded itself, half the time it refuses to launch and I get this error:
![Screenshot 2023-10-30 185415](https://github.com/Reloaded-Project/Reloaded-II/assets/32623258/b309a708-64e1-4e75-80d5-ae597bebc23c)

**Comment by Sewer56** [comment]
Cause of this is still unknown, it's believed to be external software interference. 
Generally people have had success with extracting a [fresh copy of Reloaded](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.0/Release.zip) ontop of their existing one.

Consider also checking your Antivirus logs.

**Comment by LShirohana** [comment]
> Cause of this is still unknown, it's believed to be external software interference. Generally people have had success with extracting a [fresh copy of Reloaded](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.0/Release.zip) ontop of their existing one.
> 
> Consider also checking your Antivirus logs.

I ran into this issue too, and was going to debug it, but had issues building locally so I can attach VS debugger, so instead I give up for now and wanted to ask some questions. Did you ever look into this and have some ideas? Do you think Defender is interfering with your hooks for LoadLibraryW and such? Or do you just not really know the cause?

**Comment by Sewer56** [comment]
Historically it was caused by defender interfering with `Kernel32AddressDumper.exe`. I'm not sure in which exact way as I never tried looking into it too deep. 

I never proceeded much with it because I was doing some work on [Reloaded.Injector](https://github.com/Reloaded-Project/Reloaded.Injector/tree/2.0.0), I figured out a trick to actually make it inject code into a suspended process without spawning a separate process. (This is tricky for the 64-bit host, 32-bit child process situation).

The work there was mostly ready, I just never got around to carrying it over the finish line. I've been spending my past few months porting libraries to Rust (mostly hooks... it's massive...), for Reloaded-II's eventual successor; so R2 effectively fell into maintenance mode where I fix major showstoppers. I hope to have R3 ready in 2 years from now. 

(I'm a dev team of 1, so it'll take some time, the fact I can consistently dedicate 30+ hours a week on development ontop of my full time job is kind of a miracle, may need a break soon though, after doing that for over half a year, it's taking a small toll on me mentally).

**Comment by LShirohana** [comment]
Of course, I saw the post in another issue of you working on R3, and that is why I was just lookin' into it to see if I can debug it myself and submit a simple PR. Also, if you would like some help with R3, I have experience with windows internals to a small degree/reverse engineering, and it would be a fun project to work on it sounds like, plus gives me a reason to learn rust rather than keep working with C++/asm solely.

I'll try to see if I can fix my weird visual studio compiler error and debug why its not starting the process and such.

**Comment by Sewer56** [comment]
I'm glad, great.

Been taking a few small detours with smaller projects as a break, but once I'm done with [reloaded-hooks-rs](https://github.com/Reloaded-Project/Reloaded.Hooks-rs). (Reloaded.Hooks rewrite in Rust), I'll probably get back to writing the R3 spec. Hooks lib has been pretty huge, got around 50k lines of code over there over 5-6ish months. Docs are extremely detailed and it's cross platform AND cross architecture. Around 80% done all in all.

After that it's... make a lot of issues, break up the work, and off we go; anything will be up for grabs. When that time comes I'll take any help I can get.
