### ISSUE TITLE
'Reloaded Memory not found'

### ISSUE THREAD

**Issue by crashblaine42** [Reloaded-Project/Reloaded-II#282]
In the past, I have been able to get Reloaded to run, however as of recently I have not been able to get it to run and it will come up with the same error for both Persona 3 Portable and Persona 5 Royal. I've re-installed Reload around 4 times with all pre-requisites and dependencies in check. 
![Screenshot 2024-01-20 182455](https://github.com/Reloaded-Project/Reloaded-II/assets/157254957/6d2bd1c9-7b53-4512-a046-8f4e3893981f)
![Screenshot 2024-01-20 182509](https://github.com/Reloaded-Project/Reloaded-II/assets/157254957/8049d097-754f-4afd-a0e7-5e640c6cbbc9)
![Screenshot 2024-01-20 182539](https://github.com/Reloaded-Project/Reloaded-II/assets/157254957/e708cecd-dd90-49b0-8593-ee2c56597909)

**Comment by Sewer56** [comment]
I forgot to respond to this. 

It's unclear from the log which mod has it missing, but one of your mods got borked; either due to a false positive from your Antivirus software which deleted the file or a bad update.

In any case, I updated R2. Hopefully the error message should tell you now which mod has failed to load. Delete that mod and let the launcher re-download it.
