### ISSUE TITLE
[Stale] [User Possibly Had Launcher's Internet Access Silent Revoked via Antivirus, Leading to Missing Dependency Downloads. Unknown exact issue]

### ISSUE THREAD

**Issue by golcysdol** [Reloaded-Project/Reloaded-II#304]
![image_2024-02-20_162419029](https://github.com/Reloaded-Project/Reloaded-II/assets/160673333/584e6639-8a51-450e-a96d-717d5958f1bd)

**Comment by Sewer56** [comment]
Wow. I never expected I'd see this error.

I'm not really sure what you'd need to do to even get this error, given the files on this are available at multiple servers, and it's checked for by the launcher on every boot.

I suspect that the `Reloaded-II` launcher might not have any internet connectivity. Be it because of silent treatment from Antivirus software, or similar cause. I'm not really sure what to do myself, per-se.

As a temporary workaround, you can try pasting `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z` in your browser, but if it wasn't able to download this in the first place, well, things might be rough from here.

**Comment by golcysdol** [comment]
Yeah my antivirus nuked it but I went and gave reloaded special permission but it’s still not working.

**Comment by Sewer56** [comment]
> Yeah my antivirus nuked it but I went and gave reloaded special permission but it’s still not working.

Same error? Take a screenshot.

**Comment by golcysdol** [comment]
The screenshot I showed before is from after doing that. Before I did that it was longer because of (I assume) the mods I had downloaded. I reinstalled reloaded and got the error above.

**Comment by Sewer56** [comment]
Does pasting `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z` in browser work for you? To at least get it in a bootable state.

**Comment by golcysdol** [comment]
I’m not close to my computer right now but I’ll try that. Also I think I should mention that it’s not the first time I get an error like that. But the first time I had to reset most of my computer and I’d like to find a less extreme solution. Also this time around I couldn’t even start my game modded and got the error message from the get go.

**Comment by Sewer56** [comment]
Were you eventually successful?

**Comment by Sewer56** [comment]
Closed due to inactivity.
