### ISSUE TITLE
After Update to 1.27.0 P3R fails to start

### ISSUE THREAD

**Issue by Severus157** [Reloaded-Project/Reloaded-II#348]
After Update to 1.27.0 in Reloaded 2 P3R cannot start anymore.
Every try it comes up with the error:
"Unable to load library steamclient64.dll"

Not really sure why it happens. But only happens after the Update to the 1.27.0 Version...
Console doesn't really show the Problem and just stops. Also Reloaded 2 doesn't seem to have any kind of logging ability as there is no Log to be found anywhere.

**Comment by Sewer56** [comment]
Update 1.27.0 did not have any changes that would cause a change in loader or mod behaviour. All changes were purely in the launcher, on things unrelated to whatever happens at runtime.

Feel free to extract a fresh copy of 1.27.0: https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.0/Release.zip over your existing installation, overwriting the files, if you think your Reloaded is borked. Or a fresh copy of 1.26.2 https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.26.2/Release.zip if you think this was caused by the update, however that should not be the case.

The error is more likely to be caused by your combination of installed mods.

As for Reloaded logs, you can find them if you click `View Log Files` in the default screen of the Launcher.

![20240324_20h57m01s_Mod_Loader_Settings](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/b2ff89ae-7564-4973-8fa7-d29a8b903954)
