### ISSUE TITLE
Any time i download a mod through reloaded it crashes.

### ISSUE THREAD

**Issue by Delotree** [Reloaded-Project/Reloaded-II#367]
Title. Basically if i try to download a mod, reloaded either crashes or freezes. if i add the mod manually the mod doesnt seem to work, although the mods havent seemed to work in the first place.

these are the mods i have, if that helps.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/167729683/c8743d00-9a69-42e5-9277-fe944e64f59a)

**Comment by Sewer56** [comment]
> download a mod, reloaded either crashes or freezes.

Do you have a screenshot of a crash error?
And a link to the mod you're trying to download

**Comment by Delotree** [comment]
there's no crash error, it just closes and doesn't download the mod.
as for the mod, https://gamebanana.com/mods/444458

**Comment by Sewer56** [comment]
Does this apply to downloads in-app, or 1 click downloads?
(Or both?)

**Comment by Delotree** [comment]
1-click download works, but the mod itself doesn't work.
It looks like this now:
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/167729683/6e965434-2c82-404c-becc-1797b0434a98)

**Comment by Sewer56** [comment]
I'll try to reproduce with that specific mod later. May be today, may be tomorrow, it's not easy since I also got work to do.

In the meantime, consider extracting a fresh [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.3/Release.zip) over your existing Reloaded folder, replacing any files. And making sure your Antivirus is not silently interfering.

**Comment by Delotree** [comment]
alright, thank you. i have a feeling its a problem with my laptop, as the same thing happened with persona 3 reload. maybe i missed a step, or maybe norton isnt loving it.
