### ISSUE TITLE
MS Store/GamePass Games Locations' Cannot be Updated within Reloaded-II Due to Copy Protection/Sandboxing

### ISSUE THREAD

**Issue by z4mm** [Reloaded-Project/Reloaded-II#368]
I am having trouble launching P3R after the most recent Reloaded II update.  I do have the MS store / UWP dump version of the game and it has ran smoothly up until now. I am aware that the app folder was moved, and I get the message telling me to edit the application but  get a message telling me that the P3R file is unexcitable. I'm not too sure how to fix it. 
All I can think of is just starting over from scratch with the dump and creating the path to the game. 

![IMG_4896](https://github.com/Reloaded-Project/Reloaded-II/assets/168111061/388633d9-0605-4249-ba4c-36bbc1b937a3)
![IMG_4887](https://github.com/Reloaded-Project/Reloaded-II/assets/168111061/42043037-f469-4444-96c1-6126c32f9de0)

**Comment by Sewer56** [comment]
Ah, I suppose there's a user experience flaw there.

Nothing I can do about the dialog failing though, Copy Protection/Sandboxing built into Windows prevents external stuff from reading the files, and that includes Windows' own file open dialog. I do know a workaround however.

In the meantime, here's what you can do.
The location path is also editable by hand, without the 'update' button. If you copy and paste the path to your `P3R.exe` into that box, and restart the launcher, you should be ok. 

Otherwise, if copying in App doesn't work, go to `Reloaded-II/Apps/p3r_exe/App.json` (should be called that from memory). And inside that file, edit the path while the launcher is closed. Then restart the launcher.

I'll try to patch this up over the weekend, but in the meantime, if you manually change the path outside of the launcher, you should be OK.

**Comment by Sewer56** [comment]
Fixed in 1.27.4: [Changelog](https://github.com/Reloaded-Project/Reloaded-II/discussions/369)
