### ISSUE TITLE
Request: Please add the ability to add a seperate display name argument for the enumarable type in config.cs

### ISSUE THREAD

**Issue by TheBestAstroNOT** [Reloaded-Project/Reloaded-II#385]
In the configuration part of the mod please add an option to add a seperate display argument while rn it directly displays the name of the ENUM itself. like this: -
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/139786546/ef2c5f07-090e-44cc-ba33-eb23ad375e17)
It would be better if with an argument you can add a prettier better looking version of the enum

**Comment by Sewer56** [comment]
I'd gladly take a PR for it, however, I'm not planning on adding any major functionality myself.
All of my focus is on Reloaded3, which I'm spending 25-30 hours a week on after work.
(Pretty much, I don't have a life)

You'd need to do the following:

- Fork my Fork of Fork of Handy Control: https://github.com/Sewer56/HandyControl
- Use some existing runtime built-in attribute to specify the names of the enum entries.
- In the code that creates the `PropertyGrid`, check that attribute for enums.
- Update the mod template to note the new behaviour.

**Comment by TheBestAstroNOT** [comment]
umm this is a bit out of my league

**Comment by TheBestAstroNOT** [comment]
@Sewer56 Do you know if there is a way we can call functions from other files in config.cs. That way i can fix this issue

**Comment by Sewer56** [comment]
Do you mean:
1. Call a function based on what the enum is set to?
2. Set a function to determine the member name?

## 1. Call function based on Value

You can make a method which checks your config, and then runs some code based on the values.
Put that in a separate method that takes the config as a parameter.

Then:
- Call that method from startup at `Mod.cs`.
- Call that method from `public override void ConfigurationUpdated(Config configuration)` 

## 2. Set function to determine member name

Not currently possible, hence why this issue is open.

**Comment by TheBestAstroNOT** [comment]
I am basically making a application to act as an interface between the reloaded II config and the user.  Basically u can add options to the application and images,videos and stuff and it will interact with the config directly. I just need to either detect when the configure mod button is pressed or i need to directly call a function/exe via the config.cs file. If i can do that i can easily make it much better.

**Comment by Sewer56** [comment]
This link may help https://github.com/Reloaded-Project/Reloaded-II/discussions/379#discussioncomment-9461136

**Comment by TheBestAstroNOT** [comment]
Ok thanks
