### ISSUE TITLE
Help: "Unable to find" errors

### ISSUE THREAD

**Issue by Mingledorff1** [Reloaded-Project/Reloaded-II#393]
For every Mod for Persona 3 Reloaded, I'm getting this error when trying to launch via Reloaded.
I have tried reinstalling all of the prereqs, I have tried uninstalling and reinstalling the game. 
Not just with the femc mod, pops up with any mods I've tried.
Not sure why it can't find the mods or whatever it is thats going on.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/172426957/f929f902-61c0-41db-bfde-29ae85bf650d)

**Comment by Sewer56** [comment]
Open an issue in the mod author's project 
https://github.com/MadMax1960/Femc-Reloaded-Project

I'm guessing it's a game version mismatch of sorts, but ideally the mods should be able to cover multiple versions of each game. Maybe the authors got the signatures wrong.

**Comment by Sewer56** [comment]
I am more curious myself if anything.

Even if these guys built it for latest Steam version and you used latest GamePass and they were slightly different, I imagine most of the signatures would still match up.

I can procure the MS version of the game temporarily if needed, since that typically ends up being the black sheep, but I'm more curious than anything as to why nothing's being found. I can't imagine a world where you're not launching P3R.exe at least.

If you're on the MS Store version, have you tried `Edit Application -> Deploy ASI Loader`? And then checking 'don't inject'. That should automatically happen on adding game, but in the case it didn't, and the code's being injected into that program that shows the little banner, it would explain the failure.

**Comment by Mingledorff1** [comment]
Okay there we go, that did it, thank you so much. It never required me to do that before, and it just worked, so I dunno why that was, but by changing the settings you mentioned it is all good now! I spent the last like 4 days trying to search around and see if anyone else had that issue but didn't find anything, should have just came here in the first place lol. Thank you again 🙏

**Comment by Sewer56** [comment]
Ah, no worries.

I'm really curious why that didn't automatically kick in, normally it should. Maybe there's some sort of edge case I don't cover when trying to detect if it's an Xbox game. Or maybe the files were just unprotected before.

If it works, it works 👍
