### ISSUE TITLE
Bug: Metaphor deploy ASI Loader does not create the dll file

### ISSUE THREAD

**Issue by McMarius11** [Reloaded-Project/Reloaded-II#474]
**Describe the Bug**
Metaphor deploy ASI Loader does not create the dll file

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Metaphor
2. Click on Deploy ASI Loader

**Expected Behaviour**
It should create the ASI and a dll file

**Screenshots**
![metaphor_reload2](https://github.com/user-attachments/assets/19ffff05-1c76-45d0-bf15-05d7827959e5)

**Additional Context**
Same issue on Windows & Linux

**Comment by Sewer56** [comment]
This happens when Reloaded thinks there's already an ASI Loader in your game folder.
Seems to be working as intended, but to screenshot your game folder nonetheless.

----

Existing loader detection is done by comparing the exports of the EXE file (possible loader names) against what's already in the folder. If one of the files is already there; it's assumed the user manually installed ASI Loader.

**Comment by McMarius11** [comment]
![metaphor_folder](https://github.com/user-attachments/assets/690e1857-5f3d-45cf-b411-1b2a591e7e33)

thanks for the answer  @Sewer56 , this is my folder

**Comment by Sewer56** [comment]
Oh, maybe it's because there was already an `.asi` file by the time you first deployed. The specific heuristic it uses is seeing if there is any `.asi` file in either:

- Game Folder
- `scripts` folder
- `plugins` folder

If any `.asi` files exist in any of the folders, no new loader is installed. Just delete the .asi file placed by the loader; should do it right next time.

**Comment by McMarius11** [comment]
thanks @Sewer56, i had a .asi file in a different folder ind the same root, i thought i would only look into the main folder.

now i can start the game from steam and get the mods to work +1: , if i started the game right in the launcher the shadows were completely bugged.
