### ISSUE TITLE
Help: The type initializer for 'System.Management.ManagementPath' threw an exception

### ISSUE THREAD

**Issue by toxicjackal** [Reloaded-Project/Reloaded-II#59]
Hi, I don't code at all, and I have no idea how to even begin to read the error messages I'm getting.

![](https://i.imgur.com/WOkAnZt.png)

I've installed all 4 prerequisites (and reinstalled them as well). Every time I try to run Reloaded II, as an administrator or otherwise, this series of errors happen. 

I am on a Win 7 machine. The program loaded without issue on my Win 10, even though I did everything the same. Please help?

**Comment by Sewer56** [comment]
This should have been fixed for Wine and Modified/Certain Editions of Windows OS in 1.7.0 but it seems I forgot to patch a single other piece of code that triggered the issue.

Try running this build:
[Release.zip](https://github.com/Reloaded-Project/Reloaded-II/files/5467234/Release.zip)

Otherwise you can simply run Reloaded without Admin. Reloaded does not require admin, unless the program/game itself you're using it with requires admin (this is sometimes the case due to DRM or AntiCheat for Multiplayer Components).

**Comment by toxicjackal** [comment]
That worked! Thank you so much!
