### ISSUE TITLE
Help: Tried to launch Sonic Heroes, gets error message: Failed to start the process. Is your path correct?

### ISSUE THREAD

**Issue by SonicHeroesEnthusiast** [Reloaded-Project/Reloaded-II#62]
Hello everyone! 

I've been trying to play Sonic Heroes with a few mods, but a specific error message keeps popping up whenever I try to launch the application. 

I also don't understand coding at all (I barely passed Computer Science 2 ^_^'), which makes me unable to decipher the error text. 

**Did you install the Prerequisites?**
Yes. I am running on a Windows 10 computer. 

**Describe the Issue**
I tried to play Sonic Heroes by clicking the "Launch Application" button, as hinted at in the instructions. However, I then get an error message saying: "Failed to start the process. Is your path corrrect?" and then Reloaded II closes. 

**Screenshots**

![sonic heroes launch error data](https://user-images.githubusercontent.com/74950691/100056332-849b3880-2df3-11eb-826e-19cc4c4869b5.PNG)

**Additional Resources**

I also looked through my computer's event viewer to get additional details on what went wrong. Here's something I found at the same time as the "crash". 

![sonic heroes launch error data 2](https://user-images.githubusercontent.com/74950691/100056723-24f15d00-2df4-11eb-8e7e-6d2ecdf6a3f3.PNG)

Thanks you guys!

**Comment by Sewer56** [comment]
It failed to run the game executable (for whatever reason).
What I'd advise checking is the following:
- Right click `TSonic_win -> Properties -> Compatibility` and check if the game set to run as Admin. If it is, uncheck it (not needed) or run Reloaded as admin otherwise.
- In that same effort, if `Compatibility Mode` is enabled, try disabling it.
- Last thing that comes to mind is the game executable; the community uses the NoCD Crack (which also SEGA officially distributes in the "Sonic PC Collection") as the DRM used in the US release has been blacklisted by Microsoft due to unpatched security exploits\*. MD5 Checksum of this EXE is `23c3fb873c614e15dae1f362e7a15831` if you wish to compare.

*(As usual, in one way or another intrusive anti-consumer DRM eventually fails and locks legitimate customers forever. This will probably also happen to Denuvo in the long future and games may not be preserved.)*

**Comment by SonicHeroesEnthusiast** [comment]
YEEEEEEEEEEESSSSSSSSSSSSSSSSSSS!!!!!!!!! THAT WORKED!!!!!! OMG thanks you guys so much!!!!!!!! 
:D :D :D
