### ISSUE TITLE
Bug: One or more errors occured.(failed to verify the root directory of local source) Happens when I launch the reloaded II and click the download mods>

### ISSUE THREAD

**Issue by akangmuin** [Reloaded-Project/Reloaded-II#65]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected Behaviour**

**Screenshots**

**Additional Context**

**Comment by akangmuin** [comment]
and this is when I tried to launch the P4G.exe
https://drive.google.com/file/d/1cDr2x1HbNjPQkI47LFXP6KuKN1Sl3eJS/view?usp=sharing

**Comment by Sewer56** [comment]
Can you take a screenshot of `%AppData%\Reloaded-Mod-Loader-II\ReloadedII.json` for me very please.

As for the second one, no guarantee here but can you right click the game and check if admin/compatibility mode are set. Generally it's either that, or the game was moved after it was added to Reloaded.

**Comment by akangmuin** [comment]
https://drive.google.com/file/d/1jKY-iG3LBepd06WFTekZw5a6vq16OYHU/view?usp=sharing

for reloaded.json

as for RUn As Admin I already do that, and the game never moved from my Local disk D

**Comment by Sewer56** [comment]
Okay, the first one is related to the `Configure Sources` menu.
![image](https://user-images.githubusercontent.com/6697380/102226673-9185e600-3ee0-11eb-93af-4537efa02f29.png)

Adding alternative package sources was an experimental feature added in 1.7 and no proper validation or error was added to stop users from adding invalid URLs.

To fix that, simply remove the 2 `null` entries under NuGetFeeds in the JSON and you should be good.

It was meant to be fixed a while back but my life got sidetracked and an update to the launcher has been delayed for around 2-3 months now.

Normally it's triggered by going to `Configure Sources` pressing `Add` and leaving the menu without adding any details. It's still a great mystery to me as to why only Persona users are experiencing this, and it's always 2 blank entries every time while end users claim to never have even entered the menu,

As for the latter; no idea yet. The way it works is you should run Reloaded as admin if the game is set to run as admin. Otherwise you can run Reloaded without admin. It also can be compatibility mode set on `P4G.exe`; or if you have some kind of special setup like game on network drive, it might be a good point to bring that up too.

**Comment by akangmuin** [comment]
> Okay, the first one is related to the `Configure Sources` menu.
> ![image](https://user-images.githubusercontent.com/6697380/102226673-9185e600-3ee0-11eb-93af-4537efa02f29.png)
> 
> Adding alternative package sources was an experimental feature added in 1.7 and no proper validation or error was added to stop users from adding invalid URLs.
> 
> To fix that, simply remove the 2 `null` entries under NuGetFeeds in the JSON and you should be good.
> 
> It was meant to be fixed a while back but my life got sidetracked and an update to the launcher has been delayed for around 2-3 months now.
> 
> Normally it's triggered by going to `Configure Sources` pressing `Add` and leaving the menu without adding any details. It's still a great mystery to me as to why only Persona users are experiencing this, and it's always 2 blank entries every time while end users claim to never have even entered the menu,
> 
> As for the latter; no idea yet. The way it works is you should run Reloaded as admin if the game is set to run as admin. Otherwise you can run Reloaded without admin. It also can be compatibility mode set on `P4G.exe`; or if you have some kind of special setup like game on network drive, it might be a good point to bring that up too.

Thanks a lot, kind sir. It's working now. The null is erased and I tried delete the json and launch a new fresh reloaded. It's working now. thank you so much
