### ISSUE TITLE
Error message when mods enabled

### ISSUE THREAD

**Issue by SadArya** [Reloaded-Project/Reloaded-II#67]
I can launch Persona from R2 only if there is no mod enabled if I try to enable some I get this error message:

https://prnt.sc/wc3o3q 

I tried reinstalling all of the prerequisites, adding the program to my AV's exception list, running it as an admin and nothing changed.

**Comment by Sewer56** [comment]
Can you swing by the Discord? This might require a few messages to fix up.

The file parser used by Steam Hook (the mod that lets you play without starting the game via Steam) is failing to parse an entry; probably because it was corrupt or something at some point.

**Comment by Sewer56** [comment]
Possible Steam bug from converting from `gcf` to `acf` with old installations where the name of the application is not transferred over.

In this case the culprit was `appmanifest_310.acf` which was easily solved by removing the file and reinstalling on steam which created a new manifest. 

(Steam found existing files, no data was actually downloaded)

I'll probably throw a small PR to [Steam-Apps-Management-API](https://github.com/Indieteur/Steam-Apps-Management-API) and later close the issue.
