### ISSUE TITLE
Bug: Launch from Steam shortcut error.

### ISSUE THREAD

**Issue by Glibgork** [Reloaded-Project/Reloaded-II#68]
**Describe the Bug**
The Steam shortcut isn't working properly. I have ensured that my paths and additional commands for launch are correct. I have redone it several times to make sure. If I have the console open, it will launch another, but when I attempt the launch with no console open it produces the error. It launches fine from the console, but not from the steam shortcut. I also attempted the launch with no mods selected, only the steam hook selected, and all selected. They all produced the same result.

**To Reproduce**
1. Follow steps to add an external Steam application
2. Change the launch options to "-launch 'Appdirectory\P4G.exe'"
3. Make sure Reloaded is not running and Launch the application through steam
4. Steam will freeze and produce the error after several seconds.

**Expected Behaviour**
After selecting play the application P4G.exe should start.

**Screenshots**
![Error](https://user-images.githubusercontent.com/76831637/103434059-273ea680-4c3f-11eb-9018-1d4c860c47ad.PNG)
![Error2](https://user-images.githubusercontent.com/76831637/103434062-36bdef80-4c3f-11eb-83f9-2901919cfa09.PNG)

**Additional Context**
N/A

**Comment by Sewer56** [comment]
I can't personally reproduce

![P4G_gccK0xs8iZ](https://user-images.githubusercontent.com/6697380/103439166-792cff80-4c32-11eb-8e3b-c924a0c005e2.png)


Maybe it was a one off due to config corruption (https://github.com/Reloaded-Project/Reloaded-II/issues/34)?
That one's still an enigma; sometimes the launcher will seemingly write an empty file in the place of the config.
