### ISSUE TITLE
Help: Please help me with finding the Reloaded-II.exe file

### ISSUE THREAD

**Issue by badaboom224** [Reloaded-Project/Reloaded-II#69]
I cannot seem to find the Reloaded-II.exe file in the folder. At first, I did not download the dependencies. Then I deleted the files and made sure to download all of the dependencies. Did I do anything wrong when downloading the .zip file? I have provided two screenshots below to show my issue. 

![2021-01-04 (2)](https://user-images.githubusercontent.com/76968646/103570441-b42b6f00-4e8e-11eb-92b4-fc605c7e7c41.png)
![2021-01-04 (3)](https://user-images.githubusercontent.com/76968646/103570443-b4c40580-4e8e-11eb-8b00-08a3268ea0fb.png)

EDIT: I took different screenshots for privacy reasons.

**Comment by Sewer56** [comment]
You downloaded the source code instead of the pre-build mod loader.

When you are on the main Reloaded Github page, please see `Releases` on the bottom right 
![image](https://user-images.githubusercontent.com/6697380/103570803-a8a56b80-4ec1-11eb-9b0c-da2cf62ee42c.png)

And download the first release from there.

**Comment by badaboom224** [comment]
I see it now. Thank you for your help.
