### ISSUE TITLE
Bug: IReloadedHooks type name conflict

### ISSUE THREAD

**Issue by TGEnigma** [Reloaded-Project/Reloaded-II#77]
**Describe the Bug**
There is a type name conflict between Reloaded.Hooks.ReloadedII.Interfaces.IReloadedHooks and Reloaded.Hooks.Definitions.IReloadedHooks. This leads to a null reference exception when trying to retrieve the shared controller, as they are not identical. 
Additionally, these 2 namespaces have to be used in tandem, guaranteeing conflicts.

**Expected Behaviour**
These types should either be identical (and thus be able to be used interchangably) or have different names.

**Comment by Sewer56** [comment]
Forgot to reply.

This issue actually belongs in [Reloaded.SharedLib.Hooks](https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII).

What happened here is that originally, `IReloadedHooks` was part of `Reloaded.SharedLib.Hooks.Interfaces`, but then seeing the utility of the interface; it was moved to the main `Reloaded.Hooks` library, to the `Reloaded.Hooks.Definitions` namespace.

However, in order to not break backwards compatibility with older mods, which expect `Reloaded.Hooks.ReloadedII.Interfaces.IReloadedHooks`, [that interface was aliased to the one in `Reloaded.Hooks.Definitions` by using inheritance](https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/blob/master/Reloaded.Hooks.ReloadedII/ReloadedHooks.cs) [(2)](https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/blob/master/Reloaded.Hooks.ReloadedII.Interfaces/IReloadedHooks.cs).

The two interfaces are actually, in fact identical because the implementation used is from main `Reloaded.Hooks` library, they only differ in name.

If it's necessary I could just register this interface again under the other name [here](https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/blob/6d4778ad9beb41257c3314eedd6cfde528cf2056/Reloaded.Hooks.ReloadedII/Program.cs#L23) so you could request either but the two are basically the same aside from namespace.

**Comment by TGEnigma** [comment]
Registering the interface under both names would resolve the conflict without breaking backwards compatibility, so to me this seems like the best solution.

**Comment by Sewer56** [comment]
I did it a few days ago; should be good now.
