### ISSUE TITLE
Windows Defender reporting Reloaded II as  Trojan:Win32/Wacatac.D!ml 

### ISSUE THREAD

**Issue by BulletStation** [Reloaded-Project/Reloaded-II#95]
While updating Reloaded ii to the latest release with the Steam DRM features through the app, the file "Appdata\Local\Onova\Reloaded-II\1.10.0\ReloadedII32" was flagged as the above trojan.

**Comment by Sewer56** [comment]
That kind of thing (unfortunately) happens all the time. Windows Defender's machine learning does throw funny false positives from time to time. I remember the Dolphin Emulator devs had it tough too.

In this case this is an epic fail since `Reloaded-II32.exe` is just `apphost` from the .NET Core SDK (IIRC), not even my code.

Just report as false positive and you should be okay. Honestly I'm glad false positives for R-II are fairly rare because with the original Reloaded it felt like I had them every other week.
